# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: worker.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'worker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cworker.proto\x12\x06worker\"\x0f\n\rHealthRequest\"\x1d\n\x0bHealthReply\x12\x0e\n\x06status\x18\x01 \x01(\t\"H\n\rTransformTask\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x10\n\x08image_id\x18\x02 \x01(\t\x12\x11\n\toperation\x18\x03 \x01(\t\"p\n\x0eTransformReply\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x10\n\x08image_id\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x13\n\x0bresult_path\x18\x04 \x01(\t\x12\x13\n\x0blog_message\x18\x05 \x01(\t2\x82\x01\n\rWorkerService\x12\x34\n\x06Health\x12\x15.worker.HealthRequest\x1a\x13.worker.HealthReply\x12;\n\nSubmitTask\x12\x15.worker.TransformTask\x1a\x16.worker.TransformReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'worker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHREQUEST']._serialized_start=24
  _globals['_HEALTHREQUEST']._serialized_end=39
  _globals['_HEALTHREPLY']._serialized_start=41
  _globals['_HEALTHREPLY']._serialized_end=70
  _globals['_TRANSFORMTASK']._serialized_start=72
  _globals['_TRANSFORMTASK']._serialized_end=144
  _globals['_TRANSFORMREPLY']._serialized_start=146
  _globals['_TRANSFORMREPLY']._serialized_end=258
  _globals['_WORKERSERVICE']._serialized_start=261
  _globals['_WORKERSERVICE']._serialized_end=391
# @@protoc_insertion_point(module_scope)
